// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEefx9xxjut-xr_s17NS5zSQ77Z2sTHAI',
    appId: '1:751746148892:web:0253e97991c66d2c194dd9',
    messagingSenderId: '751746148892',
    projectId: 'squadmakers-8428c',
    authDomain: 'squadmakers-8428c.firebaseapp.com',
    storageBucket: 'squadmakers-8428c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgsEhtLcpQz7LasjtM4_0HkRsoMsuVI6Y',
    appId: '1:751746148892:android:98cef7a86ccce6d9194dd9',
    messagingSenderId: '751746148892',
    projectId: 'squadmakers-8428c',
    storageBucket: 'squadmakers-8428c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITrEM8ARzOUYtOyUOTPdaju_CuvypFvY',
    appId: '1:751746148892:ios:e3e38a233eac104b194dd9',
    messagingSenderId: '751746148892',
    projectId: 'squadmakers-8428c',
    storageBucket: 'squadmakers-8428c.appspot.com',
    iosClientId: '751746148892-jovrosn7qe1t8oe8usph3602u7n4kfd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.squadMakers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDITrEM8ARzOUYtOyUOTPdaju_CuvypFvY',
    appId: '1:751746148892:ios:e3e38a233eac104b194dd9',
    messagingSenderId: '751746148892',
    projectId: 'squadmakers-8428c',
    storageBucket: 'squadmakers-8428c.appspot.com',
    iosClientId: '751746148892-jovrosn7qe1t8oe8usph3602u7n4kfd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.squadMakers',
  );
}
